server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
  boot.message: Hello sir,Department Service Spring Cloud Busu Demo
 
  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

