server:
  port: 8282
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
  
  boot.message: Hello,Employee Service 


  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
